<?php

/**
 * Fidelity-gate fixture rows. Each row pairs the extension call with the exact
 * CLI flags that must reproduce it byte for byte; a row that is missing here is
 * an option the gate cannot catch drift on.
 *
 * Every `*.svg` in fixtures/ is additionally covered by a default-options row
 * generated by the driver, so a new document needs no entry to be gated.
 *
 * Text rows pin their font via `fontFiles` and disable the system scan, so text
 * parity depends on `tests/vendor/DejaVuSans.ttf` and nothing else — on a host
 * without that font the rows still exercise real glyphs, and they cannot silently
 * become blank-render passes.
 *
 * Copyright 2026 Fojle Rabbi (Rabib)
 * SPDX-License-Identifier: Apache-2.0
 */

declare(strict_types=1);

$f = __DIR__;
$font = dirname($f) . '/vendor/DejaVuSans.ttf';
$pinnedText = ['fontFiles' => [$font], 'loadSystemFonts' => false];
$cliText = ['--use-font-file', $font, '--skip-system-fonts'];

/* Per-file constructor/CLI defaults for the driver's auto-generated row, for a
 * document whose *default* rendering already needs to pin something: the text
 * rows are host-font dependent without this, and would render identically blank
 * on a host missing the family — a pass that exercises no text at all. */
$fileDefaults = [
    'text.svg' => ['ctor' => $pinnedText, 'cli' => $cliText],
    'writer.svg' => ['ctor' => $pinnedText, 'cli' => $cliText],
];

return [
    'rows' => [
    // Constructor option boundaries (the CLI's own parse_dpi/parse_font_size
    // ranges): at the limit, where a silently remapped value would drift.
    [
        'name' => 'dpi-min',
        'file' => "{$f}/units.svg",
        'ctor' => ['dpi' => 10],
        'cli' => ['--dpi', '10'],
    ],
    [
        'name' => 'dpi-max',
        'file' => "{$f}/units.svg",
        'ctor' => ['dpi' => 4000],
        'cli' => ['--dpi', '4000'],
    ],
    [
        'name' => 'font-size-min',
        'file' => "{$f}/text.svg",
        'ctor' => $pinnedText + ['fontSize' => 1],
        'cli' => [...$cliText, '--font-size', '1'],
    ],
    [
        'name' => 'font-size-max',
        'file' => "{$f}/text.svg",
        'ctor' => $pinnedText + ['fontSize' => 192],
        'cli' => [...$cliText, '--font-size', '192'],
    ],

    // Node export must mirror `--export-id`. `clipme` is clipped to a 30x30
    // region while its child rect spans the whole page, so a whole-document
    // paint — or a fit basis taken from the node's own bbox instead of the tree
    // size — produces visibly different bytes. `dot` overlaps that region, so a
    // sibling composited in by mistake shows up too.
    [
        'name' => 'export-id-drawing',
        'file' => "{$f}/export-id.svg",
        'renderNode' => 'clipme',
        'render' => [],
        'cli' => ['--export-id', 'clipme'],
    ],
    [
        'name' => 'export-id-page',
        'file' => "{$f}/export-id.svg",
        'renderNode' => 'clipme',
        'render' => ['exportArea' => 'page'],
        'cli' => ['--export-id', 'clipme', '--export-area-page'],
    ],
    [
        'name' => 'export-id-second-node',
        'file' => "{$f}/export-id.svg",
        'renderNode' => 'dot',
        'render' => [],
        'cli' => ['--export-id', 'dot'],
    ],
    [
        'name' => 'export-id-zoom',
        'file' => "{$f}/export-id.svg",
        'renderNode' => 'clipme',
        'render' => ['zoom' => 2.0],
        'cli' => ['--export-id', 'clipme', '--zoom', '2'],
    ],
    [
        'name' => 'export-id-width',
        'file' => "{$f}/export-id.svg",
        'renderNode' => 'clipme',
        'render' => ['width' => 150],
        'cli' => ['--export-id', 'clipme', '--width', '150'],
    ],

    // `*File` resolves relative hrefs against the file's own directory when the
    // caller set no resourcesDir, exactly as the CLI does.
    [
        'name' => 'file-relative-image',
        'file' => "{$f}/image-relative.svg",
        'viaFile' => true,
        'render' => [],
        'cli' => [],
    ],

    // Per-render options on the whole-document path.
    [
        'name' => 'background',
        'file' => "{$f}/opacity.svg",
        'render' => ['background' => '#0a0b0c'],
        'cli' => ['--background', '#0a0b0c'],
    ],
    [
        'name' => 'zoom',
        'file' => "{$f}/paths.svg",
        'render' => ['zoom' => 1.5],
        'cli' => ['--zoom', '1.5'],
    ],
    [
        'name' => 'width-only',
        'file' => "{$f}/shapes.svg",
        'render' => ['width' => 33],
        'cli' => ['--width', '33'],
    ],
    [
        'name' => 'height-only',
        'file' => "{$f}/shapes.svg",
        'render' => ['height' => 48],
        'cli' => ['--height', '48'],
    ],
    [
        'name' => 'size',
        'file' => "{$f}/gradient.svg",
        'render' => ['width' => 40, 'height' => 90],
        'cli' => ['--width', '40', '--height', '90'],
    ],

    // Text with the pinned font, and the rendering hints that reach the raster
    // path on a text document.
    [
        'name' => 'text-pinned-font',
        'file' => "{$f}/text.svg",
        'ctor' => $pinnedText,
        'cli' => $cliText,
    ],
    [
        'name' => 'text-shape-rendering',
        'file' => "{$f}/text.svg",
        'ctor' => $pinnedText + ['shapeRendering' => 'crispEdges'],
        'cli' => [...$cliText, '--shape-rendering', 'crispEdges'],
    ],
    [
        'name' => 'text-text-rendering',
        'file' => "{$f}/text.svg",
        'ctor' => $pinnedText + ['textRendering' => 'optimizeSpeed'],
        'cli' => [...$cliText, '--text-rendering', 'optimizeSpeed'],
    ],
    [
        'name' => 'text-image-rendering',
        'file' => "{$f}/text.svg",
        'ctor' => $pinnedText + ['imageRendering' => 'smooth'],
        'cli' => [...$cliText, '--image-rendering', 'smooth'],
    ],
    [
        'name' => 'text-font-family',
        'file' => "{$f}/text.svg",
        'ctor' => $pinnedText + ['fontFamily' => 'DejaVu Sans'],
        'cli' => [...$cliText, '--font-family', 'DejaVu Sans'],
    ],
    [
        'name' => 'text-languages',
        'file' => "{$f}/text.svg",
        'ctor' => $pinnedText + ['languages' => ['en', 'de']],
        'cli' => [...$cliText, '--languages', 'en,de'],
    ],
    [
        'name' => 'text-generic-families',
        'file' => "{$f}/text.svg",
        'ctor' => $pinnedText + [
            'serifFamily' => 'DejaVu Sans',
            'sansSerifFamily' => 'DejaVu Sans',
            'cursiveFamily' => 'DejaVu Sans',
            'fantasyFamily' => 'DejaVu Sans',
            'monospaceFamily' => 'DejaVu Sans',
        ],
        'cli' => [
            ...$cliText,
            '--serif-family', 'DejaVu Sans',
            '--sans-serif-family', 'DejaVu Sans',
            '--cursive-family', 'DejaVu Sans',
            '--fantasy-family', 'DejaVu Sans',
            '--monospace-family', 'DejaVu Sans',
        ],
    ],

    // Every accepted value of each rendering hint (the fidelity-oracle coverage
    // rule), on documents where the hint actually reaches the raster path.
    ['name' => 'shape-optimize-speed', 'file' => "{$f}/shapes.svg",
        'ctor' => ['shapeRendering' => 'optimizeSpeed'],
        'cli' => ['--shape-rendering', 'optimizeSpeed']],
    ['name' => 'shape-crisp-edges', 'file' => "{$f}/shapes.svg",
        'ctor' => ['shapeRendering' => 'crispEdges'],
        'cli' => ['--shape-rendering', 'crispEdges']],
    ['name' => 'shape-geometric-precision', 'file' => "{$f}/shapes.svg",
        'ctor' => ['shapeRendering' => 'geometricPrecision'],
        'cli' => ['--shape-rendering', 'geometricPrecision']],

    ['name' => 'text-optimize-speed', 'file' => "{$f}/text.svg",
        'ctor' => $pinnedText + ['textRendering' => 'optimizeSpeed'],
        'cli' => [...$cliText, '--text-rendering', 'optimizeSpeed']],
    ['name' => 'text-optimize-legibility', 'file' => "{$f}/text.svg",
        'ctor' => $pinnedText + ['textRendering' => 'optimizeLegibility'],
        'cli' => [...$cliText, '--text-rendering', 'optimizeLegibility']],
    ['name' => 'text-geometric-precision', 'file' => "{$f}/text.svg",
        'ctor' => $pinnedText + ['textRendering' => 'geometricPrecision'],
        'cli' => [...$cliText, '--text-rendering', 'geometricPrecision']],

    // `imageRendering` needs a scaled `<image>` to reach the raster path at all;
    // `image-scaled.svg` scales one small PNG by a non-integer factor. These rows
    // parse from the file so the relative href resolves the way the oracle's does.
    ['name' => 'image-optimize-quality', 'file' => "{$f}/image-scaled.svg", 'viaFile' => true,
        'ctor' => ['imageRendering' => 'optimizeQuality'],
        'cli' => ['--image-rendering', 'optimizeQuality']],
    ['name' => 'image-optimize-speed', 'file' => "{$f}/image-scaled.svg", 'viaFile' => true,
        'ctor' => ['imageRendering' => 'optimizeSpeed'],
        'cli' => ['--image-rendering', 'optimizeSpeed']],
    ['name' => 'image-smooth', 'file' => "{$f}/image-scaled.svg", 'viaFile' => true,
        'ctor' => ['imageRendering' => 'smooth'],
        'cli' => ['--image-rendering', 'smooth']],
    ['name' => 'image-high-quality', 'file' => "{$f}/image-scaled.svg", 'viaFile' => true,
        'ctor' => ['imageRendering' => 'high-quality'],
        'cli' => ['--image-rendering', 'high-quality']],
    ['name' => 'image-crisp-edges', 'file' => "{$f}/image-scaled.svg", 'viaFile' => true,
        'ctor' => ['imageRendering' => 'crisp-edges'],
        'cli' => ['--image-rendering', 'crisp-edges']],
    ['name' => 'image-pixelated', 'file' => "{$f}/image-scaled.svg", 'viaFile' => true,
        'ctor' => ['imageRendering' => 'pixelated'],
        'cli' => ['--image-rendering', 'pixelated']],

    // `fontDirs` loads a whole directory; the vendor directory supplies the
    // pinned face, and the system scan stays off so nothing else can satisfy it.
    [
        'name' => 'text-font-dirs',
        'file' => "{$f}/text.svg",
        'ctor' => ['fontDirs' => [dirname($f) . '/vendor'], 'loadSystemFonts' => false],
        'cli' => ['--use-fonts-dir', dirname($f) . '/vendor', '--skip-system-fonts'],
    ],

    // `stylesheet` takes the CSS *text*; the CLI takes a path to the same bytes.
    // The rules outrank shapes.svg's presentation attributes, so a stylesheet
    // that failed to reach the parser renders the original red/green.
    [
        'name' => 'stylesheet',
        'file' => "{$f}/shapes.svg",
        'ctor' => ['stylesheet' => file_get_contents("{$f}/res/override.css")],
        'cli' => ['--stylesheet', "{$f}/res/override.css"],
    ],
    ],

    'fileDefaults' => $fileDefaults,
];
