<?php

/**
 * toSvg-gate fixture rows: each pairs `Tree::toSvg()` options with the exact
 * `usvg` CLI flags that must reproduce the output byte for byte.
 *
 * Every `*.svg` in fixtures/ is additionally covered by a default-options row
 * generated by the driver, so the writer path of a new document is gated too.
 *
 * `useSingleQuote` has NO oracle: the `usvg` CLI hardcodes `use_single_quote:
 * false` (`crates/usvg/src/main.rs:449`) and exposes no flag for it. It is gated
 * as a self-consistency row instead — `true` must be exactly the `false` output
 * with every attribute delimiter flipped — which is what the flag does and the
 * only property an oracle-free check can pin.
 *
 * Copyright 2026 Fojle Rabbi (Rabib)
 * SPDX-License-Identifier: Apache-2.0
 */

declare(strict_types=1);

$f = __DIR__;
$font = dirname($f) . '/vendor/DejaVuSans.ttf';
$pinnedText = ['fontFiles' => [$font], 'loadSystemFonts' => false];
$cliText = ['--use-font-file', $font, '--skip-system-fonts'];

$fileDefaults = [
    'text.svg' => ['ctor' => $pinnedText, 'cli' => $cliText],
    'writer.svg' => ['ctor' => $pinnedText, 'cli' => $cliText],
];

/* The writer surface, one field at a time, plus the §10.4 boundary rows: the two
 * precision ranges at 2 and 8, and each indent field across its whole accepted
 * set (`none`, `0`–`4`, `tabs`). */
$rows = [
    ['name' => 'default', 'toSvg' => [], 'cli' => []],
    ['name' => 'preserve-text', 'toSvg' => ['preserveText' => true], 'cli' => ['--preserve-text']],
    ['name' => 'id-prefix', 'toSvg' => ['idPrefix' => 'r-'], 'cli' => ['--id-prefix', 'r-']],

    ['name' => 'indent-none', 'toSvg' => ['indent' => 'none'], 'cli' => ['--indent', 'none']],
    ['name' => 'indent-0', 'toSvg' => ['indent' => 0], 'cli' => ['--indent', '0']],
    ['name' => 'indent-1', 'toSvg' => ['indent' => 1], 'cli' => ['--indent', '1']],
    ['name' => 'indent-2', 'toSvg' => ['indent' => 2], 'cli' => ['--indent', '2']],
    ['name' => 'indent-3', 'toSvg' => ['indent' => 3], 'cli' => ['--indent', '3']],
    ['name' => 'indent-4', 'toSvg' => ['indent' => 4], 'cli' => ['--indent', '4']],
    ['name' => 'indent-tabs', 'toSvg' => ['indent' => 'tabs'], 'cli' => ['--indent', 'tabs']],

    ['name' => 'attrs-none', 'toSvg' => ['attrsIndent' => 'none'], 'cli' => ['--attrs-indent', 'none']],
    ['name' => 'attrs-0', 'toSvg' => ['attrsIndent' => 0], 'cli' => ['--attrs-indent', '0']],
    ['name' => 'attrs-1', 'toSvg' => ['attrsIndent' => 1], 'cli' => ['--attrs-indent', '1']],
    ['name' => 'attrs-2', 'toSvg' => ['attrsIndent' => 2], 'cli' => ['--attrs-indent', '2']],
    ['name' => 'attrs-3', 'toSvg' => ['attrsIndent' => 3], 'cli' => ['--attrs-indent', '3']],
    ['name' => 'attrs-4', 'toSvg' => ['attrsIndent' => 4], 'cli' => ['--attrs-indent', '4']],
    ['name' => 'attrs-tabs', 'toSvg' => ['attrsIndent' => 'tabs'], 'cli' => ['--attrs-indent', 'tabs']],

    ['name' => 'coords-prec-min', 'toSvg' => ['coordinatesPrecision' => 2],
        'cli' => ['--coordinates-precision', '2']],
    ['name' => 'coords-prec-max', 'toSvg' => ['coordinatesPrecision' => 8],
        'cli' => ['--coordinates-precision', '8']],
    ['name' => 'transforms-prec-min', 'toSvg' => ['transformsPrecision' => 2],
        'cli' => ['--transforms-precision', '2']],
    ['name' => 'transforms-prec-max', 'toSvg' => ['transformsPrecision' => 8],
        'cli' => ['--transforms-precision', '8']],

    // No oracle: see the file header.
    ['name' => 'single-quote', 'toSvg' => ['useSingleQuote' => true], 'self' => true],
];

foreach ($rows as &$row) {
    $row['file'] = "{$f}/writer.svg";
    $row['ctor'] = $pinnedText;
    $row['cli'] = [...$cliText, ...($row['cli'] ?? [])];
}
unset($row);

return ['rows' => $rows, 'fileDefaults' => $fileDefaults];
